name: Commit Automático Diario

on:
  schedule:
    - cron: '0 12 * * *'  # Se ejecuta todos los días a las 12:00 UTC

  workflow_dispatch: # Permite ejecutarlo manualmente desde la pestaña "Actions"

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar usuario de Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Obtener la fecha actual
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Agregar contribución
        run: echo "Contribución diaria $DATE" >> contribucion.txt

      - name: Hacer commit y push
        run: |
          git add contribucion.txt
          git commit -m "Contribución diaria $DATE" || echo "Sin cambios para commitear"
          git push origin main
